### ISSUE TITLE
Minor HTML corrections

### ISSUE THREAD

**Issue by csarven** [rdfostrich/article-jws2018-ostrich#1]
* Include all prefixes `as: https://www.w3.org/ns/activitystreams# oa: http://www.w3.org/ns/oa# ldp: http://www.w3.org/ns/ldp# `

* Use `abbr` eg. `<span class="abbreviation" title="Resource Description Framework">RDF</span>` --> `<abbr title="Resource Description Framework">RDF</abbr>`

* Consider using trailing slashes on empty elements eg `meta`, `link`. Not required.. just makes XML based processing not fall over out of the box.

**Comment by rubensworks** [comment]
Thanks! I'll look into resolving this in ScholarMarkdown.
